# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Mon Jul 22 21:49:32 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(661, 607)
        MainWindow.setMinimumSize(QtCore.QSize(661, 607))
        MainWindow.setMaximumSize(QtCore.QSize(661, 607))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setMinimumSize(QtCore.QSize(0, 200))
        self.logoLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        self.verticalLayout.addWidget(self.logoLabel)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.fightModeAButton = QtWidgets.QPushButton(self.groupBox)
        self.fightModeAButton.setObjectName("fightModeAButton")
        self.gridLayout.addWidget(self.fightModeAButton, 0, 0, 1, 1)
        self.fightModeBButton = QtWidgets.QPushButton(self.groupBox)
        self.fightModeBButton.setObjectName("fightModeBButton")
        self.gridLayout.addWidget(self.fightModeBButton, 0, 1, 1, 1)
        self.fightModeCButton = QtWidgets.QPushButton(self.groupBox)
        self.fightModeCButton.setObjectName("fightModeCButton")
        self.gridLayout.addWidget(self.fightModeCButton, 1, 0, 1, 1)
        self.fightModeDButton = QtWidgets.QPushButton(self.groupBox)
        self.fightModeDButton.setObjectName("fightModeDButton")
        self.gridLayout.addWidget(self.fightModeDButton, 1, 1, 1, 1)
        self.fightModeEButton = QtWidgets.QPushButton(self.groupBox)
        self.fightModeEButton.setObjectName("fightModeEButton")
        self.gridLayout.addWidget(self.fightModeEButton, 2, 0, 1, 1)
        self.fightModeFButton = QtWidgets.QPushButton(self.groupBox)
        self.fightModeFButton.setObjectName("fightModeFButton")
        self.gridLayout.addWidget(self.fightModeFButton, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.toggleSkillsButton = QtWidgets.QPushButton(self.groupBox_2)
        self.toggleSkillsButton.setObjectName("toggleSkillsButton")
        self.gridLayout_2.addWidget(self.toggleSkillsButton, 0, 1, 1, 1)
        self.changePartySkillButton = QtWidgets.QPushButton(self.groupBox_2)
        self.changePartySkillButton.setObjectName("changePartySkillButton")
        self.gridLayout_2.addWidget(self.changePartySkillButton, 0, 2, 1, 1)
        self.toggleRunButton = QtWidgets.QPushButton(self.groupBox_2)
        self.toggleRunButton.setObjectName("toggleRunButton")
        self.gridLayout_2.addWidget(self.toggleRunButton, 3, 1, 1, 1)
        self.toggleControlledDamageButton = QtWidgets.QPushButton(self.groupBox_2)
        self.toggleControlledDamageButton.setObjectName("toggleControlledDamageButton")
        self.gridLayout_2.addWidget(self.toggleControlledDamageButton, 0, 0, 1, 1)
        self.toggleSummonsButton = QtWidgets.QPushButton(self.groupBox_2)
        self.toggleSummonsButton.setObjectName("toggleSummonsButton")
        self.gridLayout_2.addWidget(self.toggleSummonsButton, 1, 0, 1, 1)
        self.toggleUltButton = QtWidgets.QPushButton(self.groupBox_2)
        self.toggleUltButton.setObjectName("toggleUltButton")
        self.gridLayout_2.addWidget(self.toggleUltButton, 1, 1, 1, 1)
        self.changeHeroSkillButton = QtWidgets.QPushButton(self.groupBox_2)
        self.changeHeroSkillButton.setObjectName("changeHeroSkillButton")
        self.gridLayout_2.addWidget(self.changeHeroSkillButton, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 150))
        self.tableWidget.setStyleSheet("selection-background-color: blue;\n"
"background-color: rgb(39, 42, 49);\n"
"font: 1em;\n"
"color: green;")
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setRowCount(4)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(4)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(75)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 661, 21))
        self.menubar.setObjectName("menubar")
        self.menuBoss_Farmer = QtWidgets.QMenu(self.menubar)
        self.menuBoss_Farmer.setObjectName("menuBoss_Farmer")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuBoss_Farmer.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Boss Farmer", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Fight Mode", None, -1))
        self.fightModeAButton.setText(QtWidgets.QApplication.translate("MainWindow", "Boss Farming", None, -1))
        self.fightModeBButton.setText(QtWidgets.QApplication.translate("MainWindow", "Auto Skill/Ultimate", None, -1))
        self.fightModeCButton.setText(QtWidgets.QApplication.translate("MainWindow", "Trial Tower", None, -1))
        self.fightModeDButton.setText(QtWidgets.QApplication.translate("MainWindow", "Chasm", None, -1))
        self.fightModeEButton.setText(QtWidgets.QApplication.translate("MainWindow", "Samuel", None, -1))
        self.fightModeFButton.setText(QtWidgets.QApplication.translate("MainWindow", "Faz as bíblia", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Bot Controls", None, -1))
        self.toggleSkillsButton.setText(QtWidgets.QApplication.translate("MainWindow", "Toggle Skills", None, -1))
        self.changePartySkillButton.setText(QtWidgets.QApplication.translate("MainWindow", "Change Party Skill", None, -1))
        self.toggleRunButton.setText(QtWidgets.QApplication.translate("MainWindow", "Toggle Run Status", None, -1))
        self.toggleControlledDamageButton.setText(QtWidgets.QApplication.translate("MainWindow", "Toggle Controlled Damage", None, -1))
        self.toggleSummonsButton.setText(QtWidgets.QApplication.translate("MainWindow", "Summon Bosses", None, -1))
        self.toggleUltButton.setText(QtWidgets.QApplication.translate("MainWindow", "Toggle Ultimate", None, -1))
        self.changeHeroSkillButton.setText(QtWidgets.QApplication.translate("MainWindow", "Change Hero Skill", None, -1))
        self.menuBoss_Farmer.setTitle(QtWidgets.QApplication.translate("MainWindow", "FIle", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("MainWindow", "Edit", None, -1))

